version: '3.9'

volumes:
  mysql_db:

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    env_file: .db.env

  redis:
    image: redis
    ports:
      - 6379:6379

  app:
    build: .
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .app.env
    volumes: 
      - ".:/app"
    ports: 
      - "3000:3000"
    depends_on:
      - db
      - redis
